/*
 * g6_arena_configs.h — controller-side panel map keyed by Arena ID.
 *
 * GENERATED by maDisplayTools/tools/gen_arena_configs.py — DO NOT EDIT.
 *
 * Sources of truth (per arena):
 *   - Geometry + Arena ID: maDisplayTools/configs/arena_registry/index.yaml
 *                          + maDisplayTools/configs/arenas/G6_<name>.yaml
 *                          (`hardware_profile` field selects topology file below)
 *   - SPI/CS topology:     maDisplayTools/configs/arena_hardware/<profile>.yaml
 *
 * To regenerate after a registry/geometry/hardware change:
 *     cd Generation\ 6/maDisplayTools/tools && python3 gen_arena_configs.py \
 *         --output ../../../docs/development/g6_arena_configs.h
 *
 * STATUS: codegen and hardware YAML data are unvalidated against firmware
 * (2026-05-15). Values mirror docs/development/g6_06-arena-firmware-interface.md
 * § Pin assignments. Confirm via a panel-ID bring-up test before relying on
 * SPI/CS bindings for production work.
 */
#ifndef G6_ARENA_CONFIGS_H
#define G6_ARENA_CONFIGS_H

#include <stdint.h>
#include <stddef.h>

typedef struct {
    uint8_t panel_row;
    uint8_t panel_col;
    uint8_t spi_bus;
    uint8_t cs_gpio;
    uint8_t cs_sub_index;
} G6PanelMapEntry;

typedef struct {
    uint8_t                 arena_id;
    const char             *display_name;
    uint8_t                 row_count;
    uint8_t                 col_count;
    uint8_t                 num_spi_buses;
    uint8_t                 panel_count;
    const G6PanelMapEntry  *panels;
} G6ArenaConfig;


static const G6PanelMapEntry g6_G6_2x10_panels[] = {
    /* col 0 */
    {0, 0, 0,   0, 0},
    {1, 0, 0,   2, 1},

    /* col 1 */
    {0, 1, 0,   5, 0},
    {1, 1, 0,   6, 1},

    /* col 2 */
    {0, 2, 0,   9, 0},
    {1, 2, 0,  10, 1},

    /* col 3 */
    {0, 3, 0,  28, 0},
    {1, 3, 0,  29, 1},

    /* col 4 */
    {0, 4, 0,  32, 0},
    {1, 4, 0,  23, 1},

    /* col 5 */
    {0, 5, 1,   0, 0},
    {1, 5, 1,   2, 1},

    /* col 6 */
    {0, 6, 1,   5, 0},
    {1, 6, 1,   6, 1},

    /* col 7 */
    {0, 7, 1,   9, 0},
    {1, 7, 1,  10, 1},

    /* col 8 */
    {0, 8, 1,  28, 0},
    {1, 8, 1,  29, 1},

    /* col 9 */
    {0, 9, 1,  32, 0},
    {1, 9, 1,  23, 1},
};

static const G6PanelMapEntry g6_G6_2x8of10_panels[] = {
    /* col 1 */
    {0, 1, 0,   5, 0},
    {1, 1, 0,   6, 1},

    /* col 2 */
    {0, 2, 0,   9, 0},
    {1, 2, 0,  10, 1},

    /* col 3 */
    {0, 3, 0,  28, 0},
    {1, 3, 0,  29, 1},

    /* col 4 */
    {0, 4, 0,  32, 0},
    {1, 4, 0,  23, 1},

    /* col 5 */
    {0, 5, 1,   0, 0},
    {1, 5, 1,   2, 1},

    /* col 6 */
    {0, 6, 1,   5, 0},
    {1, 6, 1,   6, 1},

    /* col 7 */
    {0, 7, 1,   9, 0},
    {1, 7, 1,  10, 1},

    /* col 8 */
    {0, 8, 1,  28, 0},
    {1, 8, 1,  29, 1},
};

static const G6ArenaConfig g6_arena_configs[] = {
    {
        .arena_id      = 1,
        .display_name  = "G6_2x10",
        .row_count     = 2,
        .col_count     = 10,
        .num_spi_buses = 2,
        .panel_count   = sizeof(g6_G6_2x10_panels) / sizeof(g6_G6_2x10_panels[0]),
        .panels        = g6_G6_2x10_panels,
    },
    {
        .arena_id      = 2,
        .display_name  = "G6_2x8of10",
        .row_count     = 2,
        .col_count     = 10,
        .num_spi_buses = 2,
        .panel_count   = sizeof(g6_G6_2x8of10_panels) / sizeof(g6_G6_2x8of10_panels[0]),
        .panels        = g6_G6_2x8of10_panels,
    },
    /*
     * Registered in maDisplayTools but skipped (missing hardware YAML):
     *   ID 3: G6_3x12of18 — no hardware_profile declared in geometry YAML (hardware does not exist)
     */
};

static inline const G6ArenaConfig *g6_lookup_arena(uint8_t arena_id) {
    for (size_t i = 0; i < sizeof(g6_arena_configs) / sizeof(g6_arena_configs[0]); ++i) {
        if (g6_arena_configs[i].arena_id == arena_id) return &g6_arena_configs[i];
    }
    return NULL;
}

#endif /* G6_ARENA_CONFIGS_H */
